### ISSUE TITLE
解决下吧大佬

### ISSUE THREAD

**Issue by LeenOlll** [2891954521/QUST-Assistant#5]
![IMG_20230304_142125.jpg](https://user-images.githubusercontent.com/101256892/222879911-c6a64262-0f4b-43da-a937-de5bf93d3aaa.jpg)

**Comment by LeenOlll** [comment]
![正在上传 q2{1a2c895} (1f1c0adc-bca4-447e-bbec-3b3392a5b40a id=0x7f0a03b3 tag=BaseCommentFragment)…]()
最新版本的APP，没法登录

**Comment by 2891954521** [comment]
应该是教务抽风了，软件崩溃是另外的原因😥
